#!/usr/bin/env node
// Regenerate the static documentation reader from the repository's Markdown.
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { marked } from './markdown/marked.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const docs = resolve(root, 'docs');
const escape = value => value.replace(/[&<>"']/g, char => ({
  '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'
}[char]));

async function collect(directory) {
  const files = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const path = resolve(directory, entry.name);
    if (entry.isDirectory()) files.push(...await collect(path));
    else if (entry.name.endsWith('.md')) files.push(path);
  }
  return files.sort();
}

const paths = [resolve(root, 'README.md'), resolve(root, 'RECHERCHE.md'), ...await collect(docs)];
const sections = [];
for (const path of paths) {
  const source = await readFile(path, 'utf8');
  const key = relative(docs, path).replaceAll('\\', '/');
  const title = source.match(/^#\s+(.+)$/m)?.[1] ?? key;
  const renderer = new marked.Renderer();
  function destination(href) {
    if (!href || /^(?:[a-z][a-z\d+.-]*:|\/\/|#)/i.test(href)) return href;
    const [filename, fragment] = href.split('#');
    const target = resolve(dirname(path), filename);
    if (paths.includes(target)) {
      return `document.html?doc=${encodeURIComponent(relative(docs, target).replaceAll('\\', '/'))}${fragment ? `#${fragment}` : ''}`;
    }
    return relative(docs, target).replaceAll('\\', '/') + (fragment ? `#${fragment}` : '');
  }
  renderer.link = function (token) {
    return `<a href="${escape(destination(token.href))}"${token.title ? ` title="${escape(token.title)}"` : ''}>${this.parser.parseInline(token.tokens)}</a>`;
  };
  renderer.image = token => `<img src="${escape(destination(token.href))}" alt="${escape(token.text)}" loading="lazy">`;
  const ids = new Map();
  renderer.heading = function (token) {
    const base = token.text.toLowerCase().replace(/<[^>]*>/g, '').replace(/[^\p{L}\p{N}_\-\s]/gu, '').trim().replace(/\s/g, '-');
    const count = ids.get(base) ?? 0;
    ids.set(base, count + 1);
    return `<h${token.depth} id="${escape(base + (count ? `-${count}` : ''))}">${this.parser.parseInline(token.tokens)}</h${token.depth}>`;
  };
  sections.push(`<article data-doc="${escape(key)}" data-title="${escape(title)}" hidden>
<p class="source"><a href="${escape(key)}">Markdown source</a></p>
${marked.parse(source, { renderer })}</article>`);
}

await writeFile(resolve(docs, 'document.html'), `<!doctype html>
<!-- Generated by tools/build-docs.mjs. Edit the Markdown sources instead. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Documentation · Bonsai 2 27B</title>
<link rel="stylesheet" href="web.css">
<script src="document.js" defer></script>
</head>
<body>
<a class="skip" href="#content">Skip to content</a>
<header class="site-header"><a href="index.html" class="brand">Bonsai 2 / 27B</a><a href="index.html#documents">All documents</a></header>
<main id="content" class="reader">
<noscript><p>Enable JavaScript to select a document, or follow the <a href="index.html#documents">Markdown source links</a>.</p></noscript>
<div id="document-error" hidden><h1>Document not found</h1><p>Choose a document from the <a href="index.html#documents">documentation index</a>.</p></div>
${sections.join('\n')}
</main>
<footer>Project documentation · <a href="index.html">Back to home</a></footer>
</body>
</html>
`);
console.log(`Generated docs/document.html with ${paths.length} documents.`);
